server {
    listen 80;
    root /usr/share/nginx/html;
    
    location /previews/ {
        add_header Cache-Control "no-cache, must-revalidate";
        add_header CDN-Cache-Control "no-store";
    }
    
    location /bands.json {
        add_header Cache-Control "no-cache, must-revalidate";
        add_header CDN-Cache-Control "no-store";
    }
    
    location / {
        try_files $uri $uri/ =404;
    }
}
